# Clock bridge
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Joint state bridge
- ros_topic_name: "/joint_states"
  gz_topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# Odometry bridge
- ros_topic_name: "/odometry"
  gz_topic_name: "/model/aow/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# gz topic published by TF plugin
- ros_topic_name: "tf"
  gz_topic_name: "tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# gz topic published by IMU plugin
- ros_topic_name: "imu"
  gz_topic_name: "imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# Joint command topics for Left Front (LF) leg
- ros_topic_name: "/LF_HAA_position_cmd"
  gz_topic_name: "/LF_HAA_position_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/LF_HFE_position_cmd"
  gz_topic_name: "/LF_HFE_position_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/LF_KFE_position_cmd"
  gz_topic_name: "/LF_KFE_position_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/LF_WHEEL_velocity_cmd"
  gz_topic_name: "/LF_WHEEL_velocity_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Joint command topics for Right Front (RF) leg
- ros_topic_name: "/RF_HAA_position_cmd"
  gz_topic_name: "/RF_HAA_position_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/RF_HFE_position_cmd"
  gz_topic_name: "/RF_HFE_position_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/RF_KFE_position_cmd"
  gz_topic_name: "/RF_KFE_position_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/RF_WHEEL_velocity_cmd"
  gz_topic_name: "/RF_WHEEL_velocity_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Joint command topics for Left Hind (LH) leg
- ros_topic_name: "/LH_HAA_position_cmd"
  gz_topic_name: "/LH_HAA_position_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/LH_HFE_position_cmd"
  gz_topic_name: "/LH_HFE_position_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/LH_KFE_position_cmd"
  gz_topic_name: "/LH_KFE_position_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/LH_WHEEL_velocity_cmd"
  gz_topic_name: "/LH_WHEEL_velocity_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Joint command topics for Right Hind (RH) leg
- ros_topic_name: "/RH_HAA_position_cmd"
  gz_topic_name: "/RH_HAA_position_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/RH_HFE_position_cmd"
  gz_topic_name: "/RH_HFE_position_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/RH_KFE_position_cmd"
  gz_topic_name: "/RH_KFE_position_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/RH_WHEEL_velocity_cmd"
  gz_topic_name: "/RH_WHEEL_velocity_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
